### ISSUE TITLE
Simulator performances and Isaac Sim wrapper

### ISSUE THREAD

**Issue by arsimone** [robotics-upo/hunav_sim#1]
Hi, 
thanks for this nice work. May I ask if you have any pointers on the simulator speed and/or whether it can be used for Reinforcement Learning of social robots? 
Another useful piece of info would be if you are already working or plan to work on the Isaac Sym wrapper mentioned in the paper. 

Thank you

**Comment by noeperez** [comment]
Hi!
The simulator is running at 100Hz, but the Gazebo's speed decreases with the number of simulated people. 
The system can be used for Reinforcement Learning but is up to the user to implement whatever is required. We do not provide any RL algorithm.
Finally, yes, we are already implementing the Isaac Sim wrapper but it is in a very early stage.

**Comment by arsimone** [comment]
Thank you for the quick and precise answer, it would be awesome to have an Isaac Sym wrapper, keep us posted! This could greatly improve the availability of your simulator for people more into the RL community.
