### ISSUE TITLE
time_to_reach_goal metric relies on human agents data rather than robot's

### ISSUE THREAD

**Issue by giulianodejulio** [robotics-upo/hunav_sim#3]
Hi there,

I am using your package to test my navigation algorithm. To become familiar with the metrics recording, I started by computing metrics that don't involve human agents, such as `time_to_reach_goal`. However, in `hunav_metrics.py` i see that `t1` and `t2` are computed using `agents` rather than `robot` data. I understand that you use the `header.stamp` information to compute elapsed time, yet I find it a bit misleading.

Thanks for your time.

**Comment by noeperez** [comment]
Hi!
It does not matter. The input of the functions to compute the metrics are two vectors. One for the agents data, another for the robot data along the trajectory. These vectors have the same length and the same timestamps for each time step along the trajectory. Therefore, the time elapsed is the same if you calculate it with the robot data or the agents data.
